apiVersion: v1
kind: Secret
metadata:
    name: secret-using-sops
type: Opaque
data:
    password: ENC[AES256_GCM,data:LhxKb+7H91q4UobZ2d/QbQ==,iv:JuJweTE2iBoRzFaRHrr5I6kCRE4Cg0oIz993LMUJ/TY=,tag:E9xOiT+S0vFhDl3hmIKi1A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age:
        - recipient: age1nrkzlv9fpvx4txr8h7lq3spm0ny72mft75qx0x3e2nhks2pd0emquk4e39
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdTNPaVJQcFRMU0NCa1p6
            VWxGUVdOcW5HZko0UHlGNy92WnA4OFkvWnpFClJjbzM2cEF5aE1SZlpsaWd3Ykp0
            UmJtRU1qb25nVVBnUXRVQS9nQnlaVTAKLS0tIHlSNy8yWEdmZEovS1ZMdnlIMFNi
            djBnTjUxQVV0L2FNZHJNQ0dVSzZqemMK3eHrU4VKwys6CmHpKM/DU57Gl7la7Etn
            V10KRYoe4epajZyN5Gg2bc/PJGtCT97kN9FrxygGiU4FZOKUucw3DQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2024-12-15T23:44:15Z"
    mac: ENC[AES256_GCM,data:WBmotwo8v1U+2Nela9hjNd22avHjfv5P2UnXX29NJoiF0HLckYiSZbSFL8c87lg1AnO2EjNcnRd0Q5lrrjhA2FDFs+Exaqn37GXObocJCY8xTAUTUZRnvhOp6/k2UQrMzbpmEas5CRDQPXKTsUGYsYkPlfBAFSSwq2Cm3JLG7Uc=,iv:mkdQNIamXJxQT8pw9shpkZw6eB+FUo80v5KU0Iyo1yo=,tag:E8ccYw3f0KhLiTR3/lgQEg==,type:str]
    pgp: []
    encrypted_regex: ^(data|stringData)$
    version: 3.9.1
